# Site settings
title: Pop!_OS by System76
email: cassidy@system76.com
description: >
  Official Pop!_OS documentation
baseurl: ""
url: "http://pop.system76.com" #  base hostname & protocol
separator: "&sdot;" # Used in browser/tab titles
logo: "https://system76.com/assets/icon-196.png"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM # Use GitHub markdown extensions
  syntax_highlighter: rouge

gems:
  - jekyll-redirect-from

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
  -
    scope:
      path: "docs"
    values:
      layout: docs
